### ISSUE TITLE
Trying to compile NClone from Github 

### ISSUE THREAD

**Issue by marc-at-nowhow** [mijay/NClone#2]
When trying to compile NClone in VS 2013, pulled from Github, I keep getting:

Warning	1	The referenced project '..\mijay.Utils\mijay.Utils.csproj' does not exist.	NClone.Tests
Warning	2	The referenced project '..\mijay.Utils\mijay.Utils.csproj' does not exist.	NClone.Benchmarks
Warning	3	The referenced project '..\mijay.Utils\mijay.Utils.csproj' does not exist.	NClone
Warning	4	The referenced project '..\mijay.Utils\mijay.Utils.csproj' does not exist.	NClone
Warning	5	The referenced component 'mijay.Utils' could not be found. 	NClone

How can I get around this? What is contained in "mijay.Utils" that is needed inside the NClone project(s) ? Couldn't that be included directly into NClone??

**Comment by mijay** [comment]
`mijay.Utils` is a submodule. To get it, you either should clone repository recursively with
```
git clone --recursive https://github.com/mijay/NClone.git
```
or update submodules after clone using
```
cd NClone
git submodule update --init
```

**Comment by marc-at-nowhow** [comment]
And how do I get this *without* using Git myself? I'm not a Git head - can't stand it - just tried to download your code as ZIP from this site here....

**Comment by mijay** [comment]
Then just also get code from [mijay.Utils](https://github.com/mijay/Utils) and put it in corresponding folder.

**Comment by marc-at-nowhow** [comment]
OK, that works - now I just still have references to the "Jetbrains.Annotations" package which I don't have....

**Comment by mijay** [comment]
It should come from nuget. Did you restore the packages?
