### ISSUE TITLE
Default ctor is not invoked during replication

### ISSUE THREAD

**Issue by slipdef** [mijay/NClone#4]
I understand it's by design but I don't get the point why. We have a case when a default constructor must be called, otherwise we end up with a replicated object in an invalid state.

**Comment by mijay** [comment]
The point is: replication is creating an _exact_ copy of the object, without any observable side-effects. And NClone does it by recursively clonning all fields of all objects in the object graph.

But if you are clonning all fields, you do not need/must not call a default ctor:
- if you call it before clonning the fields, then it is just a waisted work, because all ctor's initializations (except the side-effects) will be overridden;
- if you call it after clonning the fields, then the outcome of clonning will be overridden.

Can you explain why do you need to call a default ctor?

**Comment by slipdef** [comment]
During my testing NClone didn't replicate private state of an object so I thought it deals with public state only. Digging into the code later I found out that it skips delegate types (my private state consists of exactly one field of delegate type). So I agree with your reasoning about skipping default ctor while all fields are replicated. Can you share why did you decide to ignore delegates?

**Comment by mijay** [comment]
This is a part of the "conventional" replicator behavior. You can override it for a specific member using attributes, or you can try to use `Clone.ObjectIgnoringConventions` to skip this behavior at all.

If I remember correctly, the reasons why conventional and intended-to-be-default behavior skips delegates are:
- delegates are mostly used for event subscriptions, and it feels logical (and was handy for the scenarios where I used NClone) that noone is subscribed for the events of freshly created clone;
- delegates often contains a closure, and hence they hold a references to all kind of objects, which might include cyclic object graphs or even some .NET-internal structures - so clonning them might be extremely expensive and might end up in an exception. I think, I even saw such 

Actually, the first reason is more a matter of taste, and the second one hinders deep copying of the delegates, not the shallow one.

**Comment by slipdef** [comment]
Ok, thanks for the detailed explanation. Can't shallow copy be a default strategy for delegates though?
In our case shallow copy fits perfectly well as a default strategy. So using attributes doesn't make sense because we need to always remember marking delegate fields with it. Currently I'm thinking to copy ConventionalMetadataProvider code, remove ignore-delegate part (other policies like lazy detection make sense) and use ObjectReplicator directly.

**Comment by mijay** [comment]
Yep, I think that creating a custom Provider currently is the best solution.
And I also agree, that shallow copy sounds like a better choice for the conventional replication... Nevertheless changing the behavior now would be a breaking change - we need to think twice before doing it.

Can you please return to this issue back in some time and give me your feedback on using "shallow copy delegates" behavior in your app. Whether they were any drawbacks and issues.
