### ISSUE TITLE
Deep clone of structures

### ISSUE THREAD

**Issue by jpmikkers** [mijay/NClone#7]
The Clone class documentation states that it does not deep clone structures. If that's the case it's a problem because a struct can contain references to mutable objects. When someone updates those objects, your original graph will also change.

**Comment by mijay** [comment]
This is a part of the "conventional" replicator behavior. You can override it for a specific member using attributes, or you can try to use `Clone.ObjectIgnoringConventions` to skip this behavior at all.

While I agree that the situations you've described do occur, they are more common for temporary structures created mainly for optimization purposes (e.g. [`List.Enumerator`](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/List.cs)) while in the most common use-case (and [officially recommended one](https://msdn.microsoft.com/en-us/library/0taef578.aspx)) structures store just other values.

`Clone.ObjectGraph` is supposed to be useful/more convenient in "the majority of cases", which is a very wage concept of course. So I had to be opinionated while deciding its behavior, and one of the assumptions I made was that usually structures stored in object graphs are transitively immutable.
